name: CommandControl
version: '${projectVersion}'
main: me.xneox.commandcontrol.bukkit.CommandControlBukkit
api-version: 1.13

author: xNeox
description: Command whitelist, blacklist, custom tab completion and operator protection!